### ISSUE TITLE
Issue about export_inference_graph.py

### ISSUE THREAD

**Issue by zxwxz** [rky0930/yolo_v2#3]
Hi @rky0930 , 
I trying to using this framework but not fully support correctly
I can training by your config
But it fail on export inference graph
`Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 119, in <module>
    tf.app.run()
  File "/home/brian.lin/anaconda3/envs/work_py36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/export_inference_graph.py", line 115, in main
    FLAGS.output_directory, input_shape)
  File "/home/brian.lin/YOLOV2_OD/yolo_v2/research/object_detection/exporter.py", line 427, in export_inference_graph
    input_shape, optimize_graph, output_collection_name)
  File "/home/brian.lin/YOLOV2_OD/yolo_v2/research/object_detection/exporter.py", line 391, in _export_inference_graph
    initializer_nodes='')
  File "/home/brian.lin/YOLOV2_OD/yolo_v2/research/object_detection/exporter.py", line 72, in freeze_graph_with_def_protos
    optimize_tensor_layout=True)
ValueError: Protocol message RewriterConfig has no "optimize_tensor_layout" field.`

Can you take a look? I will try to compare with other model's config first

After check the code, I temporarily disable 'optimize_graph' for avoid this issue

**Comment by rky0930** [comment]
Hi, Thanks for using my code. 
I think this issue is relevant with the issue. 
https://github.com/tensorflow/models/issues/2861
it's depends on what version of TF use. 
What TF version do you use?

**Comment by minda163** [comment]
change  ‘’yolo_v2/research/object_detection/exporter.py", line 72 
`optimize_tensor_layout=True`  to  ` layout_optimizer=1`
